spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/ZeroDB
    driver-class-name: com.mysql.cj.jdbc.Driver
    schema: classpath:schema.sql
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    default-enum-type-handler: com.baomidou.mybatisplus.extension.handlers.MybatisEnumTypeHandler
server:
  port: 9092
application:
  storage:
    server-host: http://localhost:9092
  config:
    avatar:
      classpath: static/imgs/avatars/default-avatar.png
      oss-location: zero/config/avatars/default-avatar.png